apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app-monitor
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: test-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s